config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root 'posts#index'
  get 'contact/index'

  resources :posts
  resources :pictures, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true
  mount_uploader :image, ImageUploader
  has_rich_text :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index; end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    @picture = Picture.new(image_params)
    @picture.save

    respond_to do |format|
      format.json {render :json => {url: @picture.image.url(:large), picture_id: @picture.id} }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy

    respond_to do |format|
      format.json {render :json => {status: :ok} }
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, success: 'Post successfully added'
    else
      render :new, danger: 'Post not added'
    end
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'Post successfully updated'
    else
      render :edit, danger: 'Post not updated'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success:
        'Post successfully removed'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :summary, :content, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contact/index.html.erb
<h1>Contact information</h1>
<p>Our team specialize in responsive websites and mobile apps for content, community, commerce and culture</p>
<section>
  <b>E-mail: </b><%= mail_to 'kovalenkoalena789@gmail.com', 'kovalenkoalena789@gmail.com' %>
</section>
<section>
  <b>Phone: </b>+375 (29) 897-00-63
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogWithImgRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= posts_path %>">Pages</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= contact_index_path %>">Contacts</a>
          </li>
        </ul>
        <%= link_to 'New post', new_post_path, class: 'btn btn-outline-primary' %>
      </nav>
    </div>

    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert alert-<%= name %>">
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: {multipart: true} do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_area :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_area :summary, class: 'form-control' %>
  </div><br>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.rich_text_area :content, class: 'editor' %>
  </div><br>

  <div class="form-group">
    <%= form.file_field :image %>
  </div><br>

  <div class="form-group">
    <%= form.submit t('.submit', action: @post.new_record? ? 'Save' : 'Update'), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <time><%= post.created_at.to_datetime.strftime("%d %B, %Y") %></time>
      |
      <%= link_to t('common.edit'), edit_post_path(post) %>
      |
      <%= link_to t('common.remove'), post_path(post), method: :delete, data:{confirm: 'Are you sure?'} %>
    </small>
  </section>

  <section class="post-content summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
    <b>Summary:</b> <%= post.summary %>
  </section>
</article>

app/views/posts/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1><%= t('.title') %></h1>

<%= render @posts %>

app/views/posts/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <time><%= @post.created_at.to_datetime.strftime("%d %B, %Y") %></time>
      |
      <%= link_to t('common.edit'), edit_post_path(@post) %>
      |
      <%= link_to t('common.remove'), post_path(@post), method: :delete, data:{confirm: 'Are you sure?'} %>
    </small>
  </section>

  <section class="post-content">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <%= @post.content %>
  </section>
</article>